# Site settings
title: "My Blog"
description: "A project course blog"
url: "https://USERNAME.github.io" # Replace USERNAME
baseurl: ""                        # Empty for user site

# Theme via remote_theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Pagination (optional)
paginate: 5
paginate_path: "/page:num"

# Exclude _site folder from Git
exclude:
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
